import {formatAnatomyName} from './format-anatomy-name';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import type {Atlas,Concept} from './anatomy';
import {LIBRARY_KEY,atlasIndex,parseLibrary,downloadText,encodeScene,type Library,type Workspace} from './workspace-model';
interface Props {atlas:Atlas;workspace:Workspace;onRestore:(w:Workspace)=>void;onPractice:(ids:string[])=>void;selection:Concept|null;onInspect:(c:Concept)=>void}
export default function StudyLibrary({atlas,workspace,onRestore,onPractice,selection,onInspect}:Props){
 const [loaded]=useState(()=>{try{return {library:parseLibrary(atlas,localStorage.getItem(LIBRARY_KEY)??'{"version":1,"sets":[],"scenes":[]}'),warning:''};}catch{return {library:{version:1,sets:[],scenes:[]} as Library,warning:'Existing library could not be read. It is preserved until you save or import a new library.'};}});
 const [notice,setNotice]=useState(loaded.warning),[library,setLibrary]=useState<Library>(loaded.library);
 const [expanded,setExpanded]=useState<Record<string,boolean>>({}),[limits,setLimits]=useState<Record<string,number>>({});
 const latest=useRef(library),changed=useRef(false);latest.current=library;if(library!==loaded.library)changed.current=true;
 const [name,setName]=useState(''),[target,setTarget]=useState(''),[share,setShare]=useState('');const index=atlasIndex(atlas);
 useEffect(()=>{if(!changed.current)return;const t=setTimeout(()=>{try{localStorage.setItem(LIBRARY_KEY,JSON.stringify(library));}catch{setNotice('Storage unavailable. Export your library to keep it.');}},250);return()=>clearTimeout(t);},[library]);
 useEffect(()=>{const flush=()=>{if(changed.current)try{localStorage.setItem(LIBRARY_KEY,JSON.stringify(latest.current));}catch{}};window.addEventListener('pagehide',flush);return()=>{flush();window.removeEventListener('pagehide',flush);};},[]);
 const named=()=>name.trim().slice(0,80);
 const saveScene=()=>{if(!named())return;setLibrary(l=>({...l,scenes:[...l.scenes,{id:crypto.randomUUID(),name:named(),workspace}]}));setName('');setNotice('Scene saved with its camera, layers and labels.');};
 const createSet=()=>{if(!named())return;const id=crypto.randomUUID();setLibrary(l=>({...l,sets:[...l.sets,{id,name:named(),conceptIds:selection&&index.concepts.has(selection.id)?[selection.id]:[]}]}));setTarget(id);setName('');setNotice('Study set created. Select structures in Explore, then add them here.');};
 const importFile=async(file:File)=>{try{if(file.size>2000000)throw Error('File exceeds 2 MB.');const imported=parseLibrary(atlas,await file.text());const current=latest.current;const sets=[...new Map([...current.sets,...imported.sets].map(s=>[s.id,s])).values()],scenes=[...new Map([...current.scenes,...imported.scenes].map(s=>[s.id,s])).values()];if(sets.length>50||scenes.length>30)throw Error('Combined library exceeds 50 sets or 30 scenes.');setLibrary({version:1,sets,scenes});setNotice('Library imported. Existing entries with matching IDs were updated.');}catch(e){setNotice(e instanceof Error?e.message:'Could not import library.');}};
 return <section className="study-library"><h2>Sets and scenes</h2><p className="study-note">Build your own syllabus and save useful views. This library is stored in this browser.</p>
 <label>Name<input maxLength={80} placeholder="Upper-limb practical" value={name} onChange={e=>setName(e.target.value)}/></label><div className="study-actions"><Button disabled={!named()||library.sets.length>=50} onClick={createSet}>Create study set</Button><Button variant="outline" disabled={!named()||library.scenes.length>=30} onClick={saveScene}>Save current scene</Button></div>
 {library.sets.length>0&&<><label>Add selected structure to<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Choose a set</option>{library.sets.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><Button variant="outline" disabled={!selection||!target||!index.concepts.has(selection.id)||!!library.sets.find(s=>s.id===target&&(s.conceptIds.length>=500||s.conceptIds.includes(selection.id)))} onClick={()=>{if(selection)setLibrary(l=>({...l,sets:l.sets.map(s=>s.id===target?{...s,conceptIds:[...new Set([...s.conceptIds,selection.id])]}:s)}));setNotice('Selected concept added. Paired concepts can be filtered by side during practice.');}}>Add {selection?formatAnatomyName(selection.name):'selection'}</Button></>}
 <div className="library-entries">{library.sets.map(set=><details key={set.id} onToggle={e=>{const open=e.currentTarget.open;setExpanded(x=>({...x,[set.id]:open}));}}><summary>{set.name} · {set.conceptIds.length} structures</summary><div className="study-actions"><Button disabled={!set.conceptIds.length} onClick={()=>onPractice(set.conceptIds)}>Practice this set</Button><Button variant="ghost" onClick={()=>{setLibrary(l=>({...l,sets:l.sets.filter(s=>s.id!==set.id)}));setNotice('Set removed.');}}>Delete set</Button></div>{expanded[set.id]&&<ul>{set.conceptIds.slice(0,limits[set.id]??30).map(id=>{const c=index.concepts.get(id);return c&&<li key={id}><Button variant="ghost" onClick={()=>onInspect(c)}>{formatAnatomyName(c.name)}</Button><Button variant="ghost" aria-label={`Remove ${formatAnatomyName(c.name)} from ${set.name}`} onClick={()=>setLibrary(l=>({...l,sets:l.sets.map(s=>s.id===set.id?{...s,conceptIds:s.conceptIds.filter(x=>x!==id)}:s)}))}>×</Button></li>;})}{set.conceptIds.length>(limits[set.id]??30)&&<li><Button variant="outline" onClick={()=>setLimits(x=>({...x,[set.id]:(x[set.id]??30)+30}))}>Show next 30</Button></li>}</ul>}</details>)}</div>
 <h3>Saved scenes</h3>{library.scenes.length===0&&<p className="study-note">Save a scene to keep the current view and labels.</p>}{library.scenes.map(s=><div className="saved-scene" key={s.id}><Button variant="outline" onClick={()=>onRestore(s.workspace)}>{s.name}</Button><Button variant="ghost" aria-label={`Delete scene ${s.name}`} onClick={()=>setLibrary(l=>({...l,scenes:l.scenes.filter(x=>x.id!==s.id)}))}>×</Button></div>)}
 <div className="study-actions"><Button variant="outline" onClick={async()=>{const url=location.origin+location.pathname+encodeScene(workspace);setShare(url);try{await navigator.clipboard.writeText(url);setNotice('Scene link copied. It contains the view, not your revision history.');}catch{setNotice('Copy the scene link below.');}}}>Copy scene link</Button><Button variant="outline" onClick={()=>downloadText('annatlas-library.json',JSON.stringify(library,null,2))}>Export library</Button><label className="file-button">Import library<input type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f);e.target.value='';}}/></label></div>
 {share&&<label>Scene link<textarea readOnly value={share} onFocus={e=>e.target.select()} rows={2}/></label>}{notice&&<p role="status" className="study-storage-notice">{notice}</p>}
 </section>;
}
